// 1. Importation de votre client de base de données (Décommenter selon votre ORM)
// const { PrismaClient } = require('@prisma/client'); // Pour Prisma
// const prisma = new PrismaClient();
// const db = require('./models'); // Pour Sequelize
// const mongoose = require('mongoose'); // Pour Mongoose
import { ChartOfAccounts } from "./models/index.js";

import sequelize from "./config/db.js";

const baseAccounts = [
  // ==============================================================================
  // CLASSE 1 : COMPTES DE CAPITAUX
  // ==============================================================================
  {
    account_number: "101000",
    account_label: "Capital social",
    account_type: "equity",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "101300",
    account_label: "Capital souscrit - appelé, versé",
    account_type: "equity",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "104100",
    account_label: "Primes d'émission",
    account_type: "equity",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "105100",
    account_label: "Écarts de réévaluation",
    account_type: "equity",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "106100",
    account_label: "Réserve légale",
    account_type: "equity",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "106300",
    account_label: "Réserves statutaires ou contractuelles",
    account_type: "equity",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "106800",
    account_label: "Autres réserves",
    account_type: "equity",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "108000",
    account_label: "Compte de l'exploitant",
    account_type: "equity",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "110000",
    account_label: "Report à nouveau (solde créditeur)",
    account_type: "equity",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "119000",
    account_label: "Report à nouveau (solde débiteur)",
    account_type: "equity",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "120000",
    account_label: "Résultat de l'exercice (bénéfice)",
    account_type: "equity",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "129000",
    account_label: "Résultat de l'exercice (perte)",
    account_type: "equity",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "131000",
    account_label: "Subventions d'investissement",
    account_type: "equity",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "145000",
    account_label: "Amortissements dérogatoires",
    account_type: "equity",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "151100",
    account_label: "Provisions pour litiges",
    account_type: "liability",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "155000",
    account_label: "Provisions pour impôts",
    account_type: "liability",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "161000",
    account_label: "Emprunts obligataires convertibles",
    account_type: "liability",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "164000",
    account_label: "Emprunts auprès des établissements de crédit",
    account_type: "liability",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "165000",
    account_label: "Dépôts et cautionnements reçus",
    account_type: "liability",
    account_class: 1,
    can_reconcile: false,
  },
  {
    account_number: "168800",
    account_label: "Intérêts courus sur emprunts",
    account_type: "liability",
    account_class: 1,
    can_reconcile: false,
  },

  // ==============================================================================
  // CLASSE 2 : COMPTES D'IMMOBILISATIONS
  // ==============================================================================
  {
    account_number: "201100",
    account_label: "Frais de constitution",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "203000",
    account_label: "Frais de développement",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "205000",
    account_label: "Concessions, brevets, licences, logiciels",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "206000",
    account_label: "Droit au bail",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "207000",
    account_label: "Fonds commercial",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "208000",
    account_label: "Autres immobilisations incorporelles",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "211100",
    account_label: "Terrains nus",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "212000",
    account_label: "Agencements et aménagements de terrains",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "213100",
    account_label: "Bâtiments",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "213500",
    account_label: "Installations générales - aménagements des constructions",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "215400",
    account_label: "Matériel industriel",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "218100",
    account_label: "Installations générales, agencements divers",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "218200",
    account_label: "Matériel de transport",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "218300",
    account_label: "Matériel de bureau et informatique",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "218400",
    account_label: "Mobilier",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "231000",
    account_label: "Immobilisations corporelles en cours",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "261000",
    account_label: "Titres de participation",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "271000",
    account_label: "Titres immobilisés (droit de propriété)",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "275000",
    account_label: "Dépôts et cautionnements versés",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "280100",
    account_label: "Amortissements des frais d'établissement",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "280500",
    account_label: "Amortissements des concessions, brevets, licences",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "281300",
    account_label: "Amortissements des constructions",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "281500",
    account_label: "Amortissements du matériel et outillage industriels",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },
  {
    account_number: "281800",
    account_label: "Amortissements des autres immobilisations corporelles",
    account_type: "asset",
    account_class: 2,
    can_reconcile: false,
  },

  // ==============================================================================
  // CLASSE 3 : COMPTES DE STOCKS ET EN-COURS
  // ==============================================================================
  {
    account_number: "311000",
    account_label: "Matières premières",
    account_type: "asset",
    account_class: 3,
    can_reconcile: false,
  },
  {
    account_number: "321000",
    account_label: "Matières consommables",
    account_type: "asset",
    account_class: 3,
    can_reconcile: false,
  },
  {
    account_number: "331000",
    account_label: "Produits en cours",
    account_type: "asset",
    account_class: 3,
    can_reconcile: false,
  },
  {
    account_number: "335000",
    account_label: "Travaux en cours",
    account_type: "asset",
    account_class: 3,
    can_reconcile: false,
  },
  {
    account_number: "355000",
    account_label: "Produits finis",
    account_type: "asset",
    account_class: 3,
    can_reconcile: false,
  },
  {
    account_number: "370000",
    account_label: "Stocks de marchandises",
    account_type: "asset",
    account_class: 3,
    can_reconcile: false,
  },
  {
    account_number: "391000",
    account_label: "Dépréciations des matières premières",
    account_type: "asset",
    account_class: 3,
    can_reconcile: false,
  },
  {
    account_number: "397000",
    account_label: "Dépréciations des stocks de marchandises",
    account_type: "asset",
    account_class: 3,
    can_reconcile: false,
  },

  // ==============================================================================
  // CLASSE 4 : COMPTES DE TIERS
  // ==============================================================================
  {
    account_number: "401000",
    account_label: "Fournisseurs",
    account_type: "liability",
    account_class: 4,
    can_reconcile: true,
    requires_third_party: true,
  },
  {
    account_number: "403000",
    account_label: "Fournisseurs - Effets à payer",
    account_type: "liability",
    account_class: 4,
    can_reconcile: true,
  },
  {
    account_number: "404000",
    account_label: "Fournisseurs d'immobilisations",
    account_type: "liability",
    account_class: 4,
    can_reconcile: true,
  },
  {
    account_number: "408100",
    account_label: "Fournisseurs - Factures non parvenues",
    account_type: "liability",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "409100",
    account_label: "Fournisseurs - Avances et acomptes versés",
    account_type: "asset",
    account_class: 4,
    can_reconcile: true,
  },
  {
    account_number: "411000",
    account_label: "Clients",
    account_type: "asset",
    account_class: 4,
    can_reconcile: true,
    requires_third_party: true,
  },
  {
    account_number: "413000",
    account_label: "Clients - Effets à recevoir",
    account_type: "asset",
    account_class: 4,
    can_reconcile: true,
  },
  {
    account_number: "416000",
    account_label: "Clients douteux ou litigieux",
    account_type: "asset",
    account_class: 4,
    can_reconcile: true,
  },
  {
    account_number: "418100",
    account_label: "Clients - Factures à établir",
    account_type: "asset",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "419100",
    account_label: "Clients - Avances et acomptes reçus",
    account_type: "liability",
    account_class: 4,
    can_reconcile: true,
  },
  {
    account_number: "421000",
    account_label: "Personnel - Rémunérations dues",
    account_type: "liability",
    account_class: 4,
    can_reconcile: true,
  },
  {
    account_number: "425000",
    account_label: "Personnel - Avances et acomptes",
    account_type: "asset",
    account_class: 4,
    can_reconcile: true,
  },
  {
    account_number: "428200",
    account_label: "Dettes provisionnées pour congés à payer",
    account_type: "liability",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "431000",
    account_label: "Sécurité sociale (URSSAF)",
    account_type: "liability",
    account_class: 4,
    can_reconcile: true,
  },
  {
    account_number: "437000",
    account_label: "Autres organismes sociaux (Retraite/Prévoyance)",
    account_type: "liability",
    account_class: 4,
    can_reconcile: true,
  },
  {
    account_number: "438200",
    account_label: "Charges sociales sur congés à payer",
    account_type: "liability",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "442100",
    account_label: "Prélèvement à la source (Impôt sur le revenu)",
    account_type: "liability",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "444000",
    account_label: "État - Impôts sur les bénéfices (IS)",
    account_type: "liability",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "445200",
    account_label: "TVA due intracommunautaire",
    account_type: "liability",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "445510",
    account_label: "TVA à décaisser",
    account_type: "liability",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "445620",
    account_label: "TVA déductible sur immobilisations",
    account_type: "asset",
    account_class: 4,
    can_reconcile: false,
    tva_applicable: true,
  },
  {
    account_number: "445660",
    account_label: "TVA déductible sur autres biens et services",
    account_type: "asset",
    account_class: 4,
    can_reconcile: false,
    tva_applicable: true,
  },
  {
    account_number: "445670",
    account_label: "Crédit de TVA à reporter",
    account_type: "asset",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "445710",
    account_label: "TVA collectée",
    account_type: "liability",
    account_class: 4,
    can_reconcile: false,
    tva_applicable: true,
  },
  {
    account_number: "445800",
    account_label: "Taxes sur le chiffre d'affaires à régulariser",
    account_type: "liability",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "447000",
    account_label: "Autres impôts, taxes et versements assimilés",
    account_type: "liability",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "455000",
    account_label: "Associés - Comptes courants",
    account_type: "liability",
    account_class: 4,
    can_reconcile: true,
  },
  {
    account_number: "467000",
    account_label: "Autres comptes débiteurs ou créditeurs",
    account_type: "asset",
    account_class: 4,
    can_reconcile: true,
  },
  {
    account_number: "468600",
    account_label: "Divers - Charges à payer",
    account_type: "liability",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "471000",
    account_label: "Compte d'attente (à régulariser)",
    account_type: "liability",
    account_class: 4,
    can_reconcile: true,
  },
  {
    account_number: "481000",
    account_label: "Frais d'émission des emprunts",
    account_type: "asset",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "486000",
    account_label: "Charges constatées d'avance",
    account_type: "asset",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "487000",
    account_label: "Produits constatés d'avance",
    account_type: "liability",
    account_class: 4,
    can_reconcile: false,
  },
  {
    account_number: "491000",
    account_label: "Dépréciations des comptes de clients",
    account_type: "asset",
    account_class: 4,
    can_reconcile: false,
  },

  // ==============================================================================
  // CLASSE 5 : COMPTES FINANCIERS
  // ==============================================================================
  {
    account_number: "503000",
    account_label: "VMP - Actions",
    account_type: "asset",
    account_class: 5,
    can_reconcile: false,
  },
  {
    account_number: "512000",
    account_label: "Banque",
    account_type: "asset",
    account_class: 5,
    can_reconcile: true,
  },
  {
    account_number: "518600",
    account_label: "Intérêts courus à payer",
    account_type: "liability",
    account_class: 5,
    can_reconcile: false,
  },
  {
    account_number: "522000",
    account_label: "Jetons détenus",
    account_type: "asset",
    account_class: 5,
    can_reconcile: false,
  },
  {
    account_number: "530000",
    account_label: "Caisse",
    account_type: "asset",
    account_class: 5,
    can_reconcile: true,
  },
  {
    account_number: "580000",
    account_label: "Virements internes",
    account_type: "asset",
    account_class: 5,
    can_reconcile: true,
  },
  {
    account_number: "590000",
    account_label: "Dépréciations des VMP",
    account_type: "asset",
    account_class: 5,
    can_reconcile: false,
  },

  // ==============================================================================
  // CLASSE 6 : COMPTES DE CHARGES
  // ==============================================================================
  {
    account_number: "601000",
    account_label: "Achats stockés - Matières premières",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "602000",
    account_label: "Achats stockés - Autres approvisionnements",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "603100",
    account_label: "Variation des stocks de matières premières",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "603700",
    account_label: "Variation des stocks de marchandises",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "604000",
    account_label: "Achats d'études et prestations de services",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "605000",
    account_label: "Achats de matériel, équipements et travaux",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "606100",
    account_label: "Fournitures non stockables (eau, énergie)",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "606300",
    account_label: "Fournitures d'entretien et petit équipement",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "606400",
    account_label: "Fournitures administratives",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "607000",
    account_label: "Achats de marchandises",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "609000",
    account_label: "Rabais, remises et ristournes obtenus sur achats",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "611000",
    account_label: "Sous-traitance générale",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "612000",
    account_label: "Redevances de crédit-bail",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "613000",
    account_label: "Locations",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "614000",
    account_label: "Charges locatives et de copropriété",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "615000",
    account_label: "Entretien et réparations",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "616000",
    account_label: "Primes d'assurances",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "618100",
    account_label: "Documentation générale",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "621100",
    account_label: "Personnel intérimaire",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "622600",
    account_label: "Honoraires",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "623000",
    account_label: "Publicité, publications, relations publiques",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "624000",
    account_label: "Transports de biens et transports collectifs du personnel",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "625100",
    account_label: "Voyages et déplacements",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "625600",
    account_label: "Missions et réceptions",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "626000",
    account_label: "Frais postaux et de télécommunications",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "627000",
    account_label: "Services bancaires et assimilés",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "631100",
    account_label: "Taxe sur les salaires",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "633300",
    account_label: "Participation à la formation professionnelle",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "635100",
    account_label: "Impôts directs (CFE, CVAE, Taxe foncière)",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "641100",
    account_label: "Salaires, appointements",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "641400",
    account_label: "Indemnités et avantages divers",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "644000",
    account_label: "Rémunération du travail de l'exploitant",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "645000",
    account_label: "Charges de sécurité sociale et de prévoyance",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "646000",
    account_label: "Cotisations sociales personnelles de l'exploitant",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "651000",
    account_label: "Redevances pour concessions, brevets, licences",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "654000",
    account_label: "Pertes sur créances irrécouvrables",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "655000",
    account_label: "Quote-part de résultat sur opérations en commun",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "658000",
    account_label: "Charges diverses de gestion courante",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "661100",
    account_label: "Intérêts des emprunts et dettes",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "661600",
    account_label: "Intérêts bancaires",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "665000",
    account_label: "Escomptes accordés",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "671000",
    account_label: "Charges exceptionnelles sur opérations de gestion",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "675000",
    account_label: "Valeurs comptables des éléments d'actif cédés",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "681100",
    account_label: "Dotations aux amortissements (Exploitation)",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "681700",
    account_label: "Dotations pour dépréciations des actifs circulants",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "691000",
    account_label: "Participation des salariés aux résultats",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "695000",
    account_label: "Impôts sur les bénéfices (IS)",
    account_type: "expense",
    account_class: 6,
    can_reconcile: false,
    tva_applicable: false,
  },

  // ==============================================================================
  // CLASSE 7 : COMPTES DE PRODUITS
  // ==============================================================================
  {
    account_number: "701000",
    account_label: "Ventes de produits finis",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "704000",
    account_label: "Travaux",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "706000",
    account_label: "Prestations de services",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "707000",
    account_label: "Ventes de marchandises",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "708000",
    account_label: "Produits des activités annexes",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "709000",
    account_label: "Rabais, remises et ristournes accordés",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "713300",
    account_label: "Variation des en-cours de production",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "713500",
    account_label: "Variation des stocks de produits",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "721000",
    account_label: "Production immobilisée - incorporelles",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "722000",
    account_label: "Production immobilisée - corporelles",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "740000",
    account_label: "Subventions d'exploitation",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "751000",
    account_label: "Redevances pour concessions, brevets, licences",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "755000",
    account_label: "Quote-part de résultat sur opérations en commun",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "758000",
    account_label: "Produits divers de gestion courante",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "761000",
    account_label: "Produits de participations",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "765000",
    account_label: "Escomptes obtenus",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: true,
    default_tva_rate: 20.0,
  },
  {
    account_number: "768000",
    account_label: "Autres produits financiers",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "771000",
    account_label: "Produits exceptionnels sur opérations de gestion",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "775000",
    account_label: "Produits des cessions d'éléments d'actif",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "777000",
    account_label:
      "Quote-part des subventions d'investissement virée au résultat",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "781000",
    account_label: "Reprises sur amortissements et provisions (Exploitation)",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: false,
  },
  {
    account_number: "791000",
    account_label: "Transferts de charges d'exploitation",
    account_type: "revenue",
    account_class: 7,
    can_reconcile: false,
    tva_applicable: false,
  },
];

// Fonction principale pour peupler la base de données
// Adaptez "Account" au nom de votre modèle/table (ex: PlanComptable, Account, etc.)
async function seedAccounts() {
  console.log("🌱 Démarrage du seed des comptes PCG 2025...");
  await sequelize.authenticate();
  await sequelize.sync({ force: true });

  try {
    for (const account of baseAccounts) {
      // ----------------------------------------------------
      // OPTION 1 : Avec PRISMA (Recommandé)
      // ----------------------------------------------------
      /*
      await prisma.account.upsert({
        where: { account_number: account.account_number }, // Assurez-vous que ce champ est unique dans votre schéma
        update: {}, // On ne modifie pas si le compte existe déjà
        create: account,
      });
      */
      // ----------------------------------------------------
      // OPTION 2 : Avec SEQUELIZE
      // ----------------------------------------------------

      console.log("📚 Création du plan comptable PCG 2025...");
      await seedChartOfAccounts({
        where: { account_number: account.account_number },
        defaults: account,
      });

      // ----------------------------------------------------
      // OPTION 3 : Avec MONGOOSE
      // ----------------------------------------------------
      /*
      await mongoose.model('Account').findOneAndUpdate(
        { account_number: account.account_number },
        account,
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
      */
      // Simulation pour l'exemple console (à supprimer en prod)
      // console.log(`Compte traité : ${account.account_number} - ${account.account_label}`);
    }

    console.log(
      `✅ Seed terminé avec succès. ${baseAccounts.length} comptes traités.`
    );
  } catch (error) {
    console.error("❌ Erreur lors du seed :", error);
    process.exit(1);
  } finally {
    // Fermeture de la connexion (si nécessaire selon l'ORM)
    // await prisma.$disconnect();
    // await mongoose.disconnect();
  }
}

// Exécution de la fonction
seedAccounts();
